### ISSUE TITLE
Menu de la web

### ISSUE THREAD

**Issue by danielcharrua** [WCGalicia/wordcamp-galicia-2021#5]

**Comment by Jlosada64** [comment]
Hola.

Habría que evitar que el menú colapse a dos líneas:

![image](https://user-images.githubusercontent.com/82547891/122546482-4aafaf00-d02f-11eb-8198-fd0c46a3b9b5.png)

**Comment by danielcharrua** [comment]
@Jlosada64 ya esta solucionado, pero por alguna razón no actualiza el CSS la web, hay alguna caché que podría estar actuando? @unapersona
Al mirar el CSS que sale en GitHub veo que la regla es correcta, pero es como si la web no esta cargando eso... No se si no se habrá empujado el cambio desde GitHub hacia el server o si existe alguna caché en medio

**Comment by unapersona** [comment]
Hola,
el css se actualiza en automático con cada push (hay un webhook configurado que lanza https://galicia.wordcamp.org/2021/wp-admin/admin-ajax.php?action=wcrcss_webhook) o también se puede manualmente desde el panel de control:
https://galicia.wordcamp.org/2021/wp-admin/themes.php?page=remote-css (hay más info en la pestaña de ayuda).

La URL carga con un parámetro que tiene pinta es de versión:
https://galicia.wordcamp.org/2021/wp-admin/admin-ajax.php?action=wordcamp_remote_css&ver=568
