### ISSUE TITLE
Apariencia en buscadores

### ISSUE THREAD

**Issue by danielcharrua** [WCGalicia/wordcamp-galicia-2021#6]
De casualidad he encontrado esto pero es algo que se debe solucionar ASAP.

<img width="616" alt="Captura de pantalla 2021-06-21 a las 8 49 47" src="https://user-images.githubusercontent.com/31829061/122719099-052cf500-d26e-11eb-87ac-d64e84002f71.png">

**Comment by danielcharrua** [comment]
Aparentemente los datos en la web estarían correctos, será cuestión de que Google (por ejemplo) vuelva a pasar el robot y refrescar datos.

**Comment by unapersona** [comment]
Cierro porque no podemos hacer nada aquí.
