### ISSUE TITLE
Hover de enlace en pie de página

### ISSUE THREAD

**Issue by CarlosLongarela** [WCGalicia/wordcamp-galicia-2021#9]
![image](https://user-images.githubusercontent.com/2273486/123542411-c99c9a00-d749-11eb-83be-aefc6f80baf4.png)
Este enlace de pie de página al pasar el ratón por encima, casi no se lee

**Comment by unapersona** [comment]
Parece que alguien ya se lo cargó y puso el nuevo, cierro!
